# TestPlugin config
# The items that are put into the player's inventory, in the order they are listed below
# All item names must appear exactly as listed here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
items: []
# Name of the world (or worlds) in which the items are given to the player
worlds: []
# Whether or not players are forced to keep items in their inventory
# true for yes, false for no
# is true by default
force-keep-items: true
